// Aufgabe3.c
// Generated by decompiling Aufgabe3.elf
// using Reko decompiler version 0.7.1.0.

#include "Aufgabe3.h"

// 0C00:0100: FpuStack real64 fn0C00_0100(Register cui16 ax, Register byte ch, Register byte cl, Register word16 dx, Register Eq_7 bx, Register (memptr Eq_11 Eq_245) bp, Register Eq_9 si, Register Eq_10 di, Register Eq_11 es, Register (ptr Eq_12) ds, Register (ptr Eq_13) gs, FpuStack real64 rArg0)
real64 fn0C00_0100(cui16 ax, byte ch, byte cl, word16 dx, Eq_7 bx, Eq_245 Eq_11::*bp, Eq_9 si, Eq_10 di, Eq_11 es, Eq_12 * ds, Eq_13 * gs, real64 rArg0)
{
	mp16 sp_1 = fp;
	if (!SZO)
	{
		Mem350[ds:bx + di:word16] = Mem0[ds:bx + di:word16] + ax;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + ax;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al;
		byte al_362 = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al;
		Mem366[ds:bx + di:byte] = Mem361[ds:bx + di:byte] + al_362;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_362;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_362;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_362;
		ds->*((word32) si + 0x01) = ds->*((word32) si + 0x01) + dh;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_362;
		gs->*((word32) bx + ((word32) si + 0x01)) = gs->*((word32) bx + ((word32) si + 0x01)) + al_362;
		bx = DPB(bx, 0x00, 0);
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_362;
		ds->*((word32) bx + ((word32) si + 0x01)) = ds->*((word32) bx + ((word32) si + 0x01)) & (al_362 ^ 0x00);
		cui16 ax_391 = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + DPB(ax, al_362 ^ 0x00, 0);
		byte al_392 = (byte) ax_391;
		Eq_26 v33_393 = ds->*((word32) bx + ((word32) si + 0x01)) - al_392;
		ds->*((word32) bx + ((word32) si + 0x01)) = v33_393;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_392 + (v33_393 < 0x00);
		byte al_400 = (byte) (ax_391 | 0x0100);
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_400;
		ds->*((word32) si + 0x01) = ds->*((word32) si + 0x01) + dl;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_400;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_400;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_400;
		ds->*((word32) bx + ((word32) si + 0x01)) = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_400;
		ds->*((word32) si + 22) = ds->*((word32) si + 22) + ch;
		Eq_26 v43_418 = (word32) (ds->*((word32) bx + ((word32) si + 0x01))) + al_400;
		ds->*((word32) bx + ((word32) si + 0x01)) = v43_418;
		si = (word32) si + 0x01;
		sp_1 = fp - 0x03;
		es->*di = __in(dx);
		di = (word32) di + 0x01;
		ax = (cui16) ((byte) (v43_418 < 0x00) + (ax_391 | 0x0100));
	}
	else
	{
		ds->*((word32) si + 0x0015) = ds->*((word32) si + 0x0015) + ch;
		Mem437[ds:bx + si:byte] = Mem434[ds:bx + si:byte] + al;
	}
	byte al_13 = (byte) ax;
	Mem18[ss:bp + si:byte] = Mem0[ss:bp + si:byte] + al_13;
	Mem21[ds:bx + si:byte] = Mem18[ds:bx + si:byte] + al_13;
	Mem23[ds:bx + di:byte] = Mem21[ds:bx + di:byte] + al_13;
	Mem25[ds:bx + si:byte] = Mem23[ds:bx + si:byte] + al_13;
	Mem27[ds:bx + si:byte] = Mem25[ds:bx + si:byte] + al_13;
	struct Eq_269 Eq_11::* sp_28 = sp_1 - 0x02;
	(ss->*sp_28).t0000 = ss;
	Mem31[ds:bx + si:byte] = Mem29[ds:bx + si:byte] + al_13;
	Mem33[ds:bx + di:byte] = Mem31[ds:bx + di:byte] + al_13;
	byte v56_34 = Mem33[ds:bx + si:byte] + 0x6C;
	Mem35[ds:bx + si:byte] = v56_34;
	cui16 ax_38 = (byte) (v56_34 < 0x00) + ax;
	byte al_39 = (byte) ax_38;
	real64 rArg0_41 = rArg0 + (real64) Mem35[ss:bp + si:word16];
	Mem43[ds:bx + si:byte] = Mem35[ds:bx + si:byte] + al_39;
	real64 rArg0_249 = rArg0_41 + (real64) Mem43[ss:bp + si:word16];
	Mem46[ds:bx + si:byte] = Mem43[ds:bx + si:byte] + al_39;
	ss->*(sp_28 - 0x02) = es;
	Mem51[ds:bx + si:byte] = Mem49[ds:bx + si:byte] + al_39;
	Mem53[ds:bx + di:byte] = Mem51[ds:bx + di:byte] + al_39;
	Mem55[ds:bx + si:byte] = Mem53[ds:bx + si:byte] + al_39;
	Mem57[ds:bx + di:byte] = Mem55[ds:bx + di:byte] + al_39;
	Mem59[ds:bx + si:byte] = Mem57[ds:bx + si:byte] + al_39;
	Mem65[ds:bx + si:byte] = Mem59[ds:bx + si:byte] - al_39 - (dh <u 0x00);
	word16 ax_68 = ax_38 + Mem65[ds:(bx + 0xDE00) + si:word16] + Mem65[ds:bx + si:word16];
	byte al_69 = (byte) ax_68;
	Mem72[ds:bx + si:byte] = Mem65[ds:bx + si:byte] + al_69;
	Mem74[ds:bx + di:byte] = Mem72[ds:bx + di:byte] + SLICE(ax_68, byte, 8);
	ds->b0000 = ds->b0000 + al_69;
	Mem78[ds:bx + di:byte] = Mem76[ds:bx + di:byte] + al_69;
	Mem80[ds:bx + si:byte] = Mem78[ds:bx + si:byte] + al_69;
	Mem83[ds:bx - 0x40 + di:byte] = Mem80[ds:bx - 0x40 + di:byte] + cl;
	Mem85[ds:bx + si:byte] = Mem83[ds:bx + si:byte] + al_69;
	Mem88[gs:bx + si:byte] = __rol(Mem85[gs:bx + si:byte], 0x00);
	word16 ax_89;
	__arpl(ax_68, bx, &ax_89);
	Mem92[ds:bx + si:byte] = Mem88[ds:bx + si:byte] + al_69;
	word16 dx_103 = (ss->*sp_28).w0008;
	word16 ax_109 = (ss->*sp_28).w000C;
	Eq_11 si_248 = (ss->*sp_28).t0000;
	struct Eq_451 Eq_12::* bx_101 = (ss->*sp_28).ptr0006;
	Mem115[ds:bx_101 + si_248:byte] = __rol(Mem92[ds:bx_101 + si_248:byte], 0x00);
	int16 di_116 = (ss->*sp_28).w000E;
	Mem119[ds:bx_101 + si_248:byte] = __rol(Mem115[ds:bx_101 + si_248:byte], 0x00);
	struct Eq_691 Eq_11::* bp_120 = (ss->*sp_28).ptr0010;
	Mem123[ds:bx_101 + si_248:byte] = __rol(Mem119[ds:bx_101 + si_248:byte], 0x00);
	byte dh_104 = SLICE(dx_103, byte, 8);
	byte al_110 = (byte) ax_109;
	byte ah_111 = SLICE(ax_109, byte, 8);
	struct Eq_473 Eq_11::* sp_121 = &(ds->*sp_28).ptr0010;
	do
	{
		struct Eq_476 Eq_12::* bx_128 = (ss->*sp_121).w0000;
		Mem131[ds:bx_128 + si_248:byte] = __rol(Mem123[ds:bx_128 + si_248:byte], 0x00);
		struct Eq_487 Eq_11::* sp_129 = sp_121 + 0x01;
		word16 cx_132 = (ss->*sp_129).w0000;
		Mem135[ds:bx_128 + si_248:byte] = __rol(Mem131[ds:bx_128 + si_248:byte], 0x00);
		(ss->*sp_129).w0000 = di_116;
		Mem139[ds:bx_128 + si_248:byte] = __rol(Mem137[ds:bx_128 + si_248:byte], 0x00);
		(ss->*(sp_129 - 0x02)).w0000 = bp_120;
		Mem143[ds:bx_128 + si_248:byte] = __rol(Mem141[ds:bx_128 + si_248:byte], 0x00);
		(ss->*(sp_129 - 0x04)).w0000 = bx_128;
		Mem147[ds:bx_128 + si_248:byte] = __rol(Mem145[ds:bx_128 + si_248:byte], 0x00);
		(ss->*(sp_129 - 0x06)).w0000 = cx_132;
		Mem151[ds:bx_128 + si_248:byte] = __rol(Mem149[ds:bx_128 + si_248:byte], 0x00);
		Mem154[ds:bx_128 + si_248:byte] = __rol(Mem151[ds:bx_128 + si_248:byte], 0x00);
		Mem157[ds:bx_128 + si_248:byte] = __rol(Mem154[ds:bx_128 + si_248:byte], 0x00);
		Mem160[ds:bx_128 - 0x01 + si_248:byte] = __rol(Mem157[ds:bx_128 - 0x01 + si_248:byte], 0x00);
		Mem163[ds:bx_128 - 0x01 + si_248:byte] = __rol(Mem160[ds:bx_128 - 0x01 + si_248:byte], 0x00);
		Mem166[ds:bx_128 - 0x01 + si_248:byte] = __rol(Mem163[ds:bx_128 - 0x01 + si_248:byte], 0x00);
		Mem169[ds:bx_128 - 0x01 + si_248:byte] = __rol(Mem166[ds:bx_128 - 0x01 + si_248:byte], 0x00);
		Mem173[ds:bx_128 + si_248:byte] = __rol(Mem169[ds:bx_128 + si_248:byte], 0x00);
		Mem178[ds:bx_128 + si_248:byte] = __rol(Mem173[ds:bx_128 + si_248:byte], 0x00);
		byte al_179;
		byte ah_180;
		__aas(al_110, ah_111, &al_179, &ah_180);
		Mem183[ds:bx_128 + si_248:byte] = __rol(Mem178[ds:bx_128 + si_248:byte], 0x00);
		sp_121 = sp_129 - 0x06;
		Eq_626 cl_175 = (byte) cx_132;
	} while ((Mem178[ds:bx_128 + si_248:byte] & 0x00) != 0x00);
	Mem187[ds:bx_128 + si_248:byte] = Mem183[ds:bx_128 + si_248:byte] + al_179;
	Mem191[ds:bx_128 + si_248:byte] = Mem187[ds:bx_128 + si_248:byte] + al_179;
	Mem193[ds:bx_128 + si_248:byte] = Mem191[ds:bx_128 + si_248:byte] + al_179;
	byte al_194;
	byte ah_195;
	__aaa(al_179, ah_180, &al_194, &ah_195);
	Mem198[ds:bx_128 + si_248:byte] = __rol(Mem193[ds:bx_128 + si_248:byte], 0x00);
	bp_120[di_116] = bp_120[di_116] + dh_104;
	Mem203[ds:bx_128 + si_248:byte] = __rol(Mem201[ds:bx_128 + si_248:byte], 0x00);
	Mem207[ds:bx_128 + si_248:byte] = Mem203[ds:bx_128 + si_248:byte];
	byte al_208;
	__das(0x00, &al_208);
	Mem211[ds:bx_128 + si_248:byte] = __rol(Mem207[ds:bx_128 + si_248:byte], 0x00);
	bp_120[di_116] = (Eq_691) ((word32) bp_120[di_116].t0000 + 0x00C2);
	Mem216[ds:bx_128 + si_248:byte] = __rol(Mem214[ds:bx_128 + si_248:byte], 0x00);
	Mem220[ds:bx_128 + si_248:byte] = Mem216[ds:bx_128 + si_248:byte];
	byte al_221;
	__daa(0x00, &al_221);
	Mem224[ds:bx_128 + si_248:byte] = __rol(Mem220[ds:bx_128 + si_248:byte], 0x00);
	bp_120[di_116] = bp_120[di_116];
	Mem230[ds:bx_128 + si_248:byte] = __rol(Mem228[ds:bx_128 + si_248:byte], 0x00);
	Mem236[ds:bx_128 + si_248:byte] = Mem230[ds:bx_128 + si_248:byte];
	struct Eq_12 * ds_240 = (ss->*(sp_129 - 0x06)).w0000;
	bool v112_242 = (Mem236[ds_240:bx_128 + si_248:byte] & 0x00) != 0x00;
	Mem243[ds_240:bx_128 + si_248:byte] = __rol(Mem236[ds_240:bx_128 + si_248:byte], 0x00);
	word16 cx_189 = DPB(cx_132, 0xC2, 8);
	int16 ax_231 = 0x00;
	struct Eq_758 Eq_11::* sp_241 = sp_129 - 0x04;
	Eq_739 C_244 = v112_242;
	do
	{
		Mem256[ds_240:si_248 + 0x00:word16] = Mem243[ds_240:si_248 + 0x00:word16] + sp_241 + C_244;
		Eq_770 cl_260 = cl_175 << 0x01;
		ds_240 = (ss->*sp_241).w0000;
		sp_241 = sp_241 + 0x02 + ax_231 + (cl_260 <u 0x00);
		byte al_271 = ds_240->bB1E0;
		word16 cx_261 = DPB(cx_189, cl_260, 0);
		si_248.u0 = ~0x1030;
		rArg0_249 = (real64) (ds_240->*bx_128).wBFCD / rArg0_249;
		C_244 = cond(sp_241);
		ax_231 = DPB(ax_231, al_271, 0);
		cx_189 = cx_261 - 0x01;
		cl_175 = (byte) (cx_261 - 0x01);
	} while (sp_241 != 0x00 && cx_261 != 0x01);
	__outb(~0x0A, al_271);
	word16 cx_280 = cx_261 - 0x03;
	ui16 ax_290 = __inw(dx_103);
	ui16 ax_292 = ax_290 * 0x02;
	Eq_826 C_299 = cond(ax_290 * 0x02);
	do
	{
		ax_292 = ax_292 - 44946 - C_299;
		byte al_312;
		byte ah_313;
		C_299 = __aaa((byte) ax_292, SLICE(ax_292, byte, 8), &al_312, &ah_313);
		dx_103 = DPB(dx_103, 0x07, 0);
		cx_280 = cx_280 - 0x01;
	} while (ax_292 == 0x00 && cx_280 != 0x00);
	__inb(dx_103);
	ds_240->wEFCF = __ror(ds_240->wEFCF, 0x01);
	return rArg0_249;
}

